import { Injectable, signal } from '@angular/core';
import { Recipe } from '../models/recipe.model';

const STORAGE_KEY = 'recipes';

const SAMPLE_RECIPES: Recipe[] = [
  {
    id: '1',
    name: 'Avocado Toast with Poached Egg',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&q=80',
    ingredients: [
      { name: 'Sourdough bread', amount: '2', unit: 'slices' },
      { name: 'Avocado', amount: '1', unit: 'whole' },
      { name: 'Eggs', amount: '2', unit: 'whole' },
      { name: 'Lemon juice', amount: '1', unit: 'tsp' },
      { name: 'Red pepper flakes', amount: '1/4', unit: 'tsp' },
      { name: 'Salt', amount: '1/2', unit: 'tsp' },
      { name: 'Black pepper', amount: '1/4', unit: 'tsp' },
    ],
    instructions: 'Toast the sourdough bread until golden and crispy. Mash the avocado with lemon juice, salt, and pepper. Poach eggs in simmering water with a splash of vinegar for 3 minutes. Spread avocado on toast, top with poached egg, and sprinkle with red pepper flakes.',
    cookingTime: 15,
    calories: 380,
    servings: 2,
    tags: ['breakfast', 'vegetarian', 'quick'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Grilled Salmon with Asparagus',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&q=80',
    ingredients: [
      { name: 'Salmon fillet', amount: '200', unit: 'g' },
      { name: 'Asparagus', amount: '200', unit: 'g' },
      { name: 'Olive oil', amount: '2', unit: 'tbsp' },
      { name: 'Garlic', amount: '2', unit: 'cloves' },
      { name: 'Lemon', amount: '1', unit: 'whole' },
      { name: 'Dill', amount: '2', unit: 'tbsp' },
      { name: 'Salt', amount: '1', unit: 'tsp' },
    ],
    instructions: 'Preheat grill to medium-high heat. Drizzle salmon and asparagus with olive oil, minced garlic, salt, and pepper. Grill salmon for 4-5 minutes per side and asparagus for 5-6 minutes, turning occasionally. Serve with fresh dill and lemon wedges.',
    cookingTime: 25,
    calories: 520,
    servings: 2,
    tags: ['dinner', 'healthy', 'high-protein'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Creamy Tomato Pasta',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&q=80',
    ingredients: [
      { name: 'Pasta', amount: '300', unit: 'g' },
      { name: 'Crushed tomatoes', amount: '400', unit: 'g' },
      { name: 'Heavy cream', amount: '100', unit: 'ml' },
      { name: 'Garlic', amount: '3', unit: 'cloves' },
      { name: 'Onion', amount: '1', unit: 'whole' },
      { name: 'Basil', amount: '10', unit: 'leaves' },
      { name: 'Parmesan', amount: '50', unit: 'g' },
      { name: 'Olive oil', amount: '2', unit: 'tbsp' },
    ],
    instructions: 'Cook pasta al dente. Sauté diced onion and garlic in olive oil until soft. Add crushed tomatoes and simmer 10 minutes. Stir in heavy cream and season. Toss with pasta, top with fresh basil and grated parmesan.',
    cookingTime: 30,
    calories: 620,
    servings: 4,
    tags: ['dinner', 'vegetarian', 'italian'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Greek Chicken Bowl',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80',
    ingredients: [
      { name: 'Chicken breast', amount: '300', unit: 'g' },
      { name: 'Quinoa', amount: '150', unit: 'g' },
      { name: 'Cherry tomatoes', amount: '200', unit: 'g' },
      { name: 'Cucumber', amount: '1', unit: 'whole' },
      { name: 'Feta cheese', amount: '80', unit: 'g' },
      { name: 'Kalamata olives', amount: '50', unit: 'g' },
      { name: 'Tzatziki', amount: '100', unit: 'g' },
      { name: 'Oregano', amount: '1', unit: 'tsp' },
    ],
    instructions: 'Season chicken with oregano, salt, and olive oil. Grill 6-7 minutes per side. Cook quinoa. Slice cucumber, halve tomatoes. Build bowls with quinoa base, sliced chicken, veggies, feta, olives, and a generous dollop of tzatziki.',
    cookingTime: 35,
    calories: 580,
    servings: 2,
    tags: ['lunch', 'high-protein', 'mediterranean'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Banana Oat Pancakes',
    image: 'https://images.unsplash.com/photo-1565299543923-37dd37887442?w=600&q=80',
    ingredients: [
      { name: 'Ripe bananas', amount: '2', unit: 'whole' },
      { name: 'Rolled oats', amount: '100', unit: 'g' },
      { name: 'Eggs', amount: '2', unit: 'whole' },
      { name: 'Milk', amount: '60', unit: 'ml' },
      { name: 'Cinnamon', amount: '1', unit: 'tsp' },
      { name: 'Honey', amount: '2', unit: 'tbsp' },
      { name: 'Blueberries', amount: '100', unit: 'g' },
    ],
    instructions: 'Blend oats into flour. Mash bananas and combine with oat flour, eggs, milk, and cinnamon. Heat a non-stick pan over medium heat. Pour small circles of batter, cook 2-3 minutes per side until golden. Serve with honey and fresh blueberries.',
    cookingTime: 20,
    calories: 340,
    servings: 2,
    tags: ['breakfast', 'healthy', 'gluten-free'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Lentil Vegetable Soup',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80',
    ingredients: [
      { name: 'Red lentils', amount: '200', unit: 'g' },
      { name: 'Carrot', amount: '2', unit: 'whole' },
      { name: 'Celery', amount: '2', unit: 'stalks' },
      { name: 'Onion', amount: '1', unit: 'whole' },
      { name: 'Vegetable broth', amount: '1', unit: 'L' },
      { name: 'Cumin', amount: '1', unit: 'tsp' },
      { name: 'Turmeric', amount: '1/2', unit: 'tsp' },
      { name: 'Spinach', amount: '100', unit: 'g' },
    ],
    instructions: 'Sauté diced onion, carrot, and celery until soft. Add cumin and turmeric, cook 1 minute. Add lentils and broth, bring to a boil. Simmer 20-25 minutes until lentils are tender. Stir in spinach and season to taste.',
    cookingTime: 40,
    calories: 290,
    servings: 4,
    tags: ['lunch', 'vegan', 'soup'],
    createdAt: new Date().toISOString(),
  },
  // --- Snacks ---
  {
    id: '7',
    name: 'Hummus with Veggie Sticks',
    image: 'https://images.unsplash.com/photo-1534422298019-c21a5b227d56?w=600&q=80',
    ingredients: [
      { name: 'Chickpeas', amount: '400', unit: 'g' },
      { name: 'Tahini', amount: '3', unit: 'tbsp' },
      { name: 'Lemon juice', amount: '2', unit: 'tbsp' },
      { name: 'Garlic', amount: '1', unit: 'clove' },
      { name: 'Olive oil', amount: '2', unit: 'tbsp' },
      { name: 'Carrot', amount: '2', unit: 'whole' },
      { name: 'Cucumber', amount: '1', unit: 'whole' },
      { name: 'Bell pepper', amount: '1', unit: 'whole' },
    ],
    instructions: 'Blend chickpeas, tahini, lemon juice, garlic, and olive oil until smooth. Add water a tablespoon at a time until creamy. Season with salt. Cut carrots, cucumber, and pepper into sticks. Serve hummus drizzled with olive oil alongside the veggie sticks.',
    cookingTime: 10,
    calories: 220,
    servings: 4,
    tags: ['snacks', 'vegan', 'healthy'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Apple Slices with Almond Butter',
    image: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80',
    ingredients: [
      { name: 'Apple', amount: '2', unit: 'whole' },
      { name: 'Almond butter', amount: '4', unit: 'tbsp' },
      { name: 'Honey', amount: '1', unit: 'tsp' },
      { name: 'Cinnamon', amount: '1/4', unit: 'tsp' },
      { name: 'Chia seeds', amount: '1', unit: 'tsp' },
    ],
    instructions: 'Core and slice the apples into thin wedges. Arrange on a plate. Mix almond butter with a drizzle of honey and a pinch of cinnamon. Serve the almond butter as a dip alongside the apple slices, and sprinkle with chia seeds.',
    cookingTime: 5,
    calories: 280,
    servings: 2,
    tags: ['snacks', 'healthy', 'quick'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Greek Yogurt Berry Parfait',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80',
    ingredients: [
      { name: 'Greek yogurt', amount: '300', unit: 'g' },
      { name: 'Mixed berries', amount: '150', unit: 'g' },
      { name: 'Granola', amount: '60', unit: 'g' },
      { name: 'Honey', amount: '2', unit: 'tbsp' },
      { name: 'Mint leaves', amount: '5', unit: 'leaves' },
    ],
    instructions: 'Layer Greek yogurt in a glass or bowl. Add a layer of mixed berries, then granola. Repeat layers. Drizzle with honey and garnish with fresh mint. Serve immediately so the granola stays crunchy.',
    cookingTime: 5,
    calories: 310,
    servings: 2,
    tags: ['snacks', 'breakfast', 'vegetarian'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Peanut Butter Energy Balls',
    image: 'https://images.unsplash.com/photo-1622484212850-eb596d769edc?w=600&q=80',
    ingredients: [
      { name: 'Rolled oats', amount: '150', unit: 'g' },
      { name: 'Peanut butter', amount: '120', unit: 'g' },
      { name: 'Honey', amount: '60', unit: 'ml' },
      { name: 'Dark chocolate chips', amount: '60', unit: 'g' },
      { name: 'Chia seeds', amount: '2', unit: 'tbsp' },
      { name: 'Vanilla extract', amount: '1', unit: 'tsp' },
    ],
    instructions: 'Mix oats, peanut butter, honey, chocolate chips, chia seeds, and vanilla in a bowl until well combined. Refrigerate for 30 minutes. Roll into balls about 3 cm wide. Store in the fridge for up to 1 week.',
    cookingTime: 15,
    calories: 180,
    servings: 12,
    tags: ['snacks', 'no-bake', 'high-protein'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '11',
    name: 'Guacamole & Tortilla Chips',
    image: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=600&q=80',
    ingredients: [
      { name: 'Ripe avocados', amount: '3', unit: 'whole' },
      { name: 'Lime juice', amount: '2', unit: 'tbsp' },
      { name: 'Red onion', amount: '1/2', unit: 'whole' },
      { name: 'Tomato', amount: '1', unit: 'whole' },
      { name: 'Fresh coriander', amount: '3', unit: 'tbsp' },
      { name: 'Jalapeño', amount: '1', unit: 'whole' },
      { name: 'Tortilla chips', amount: '100', unit: 'g' },
    ],
    instructions: 'Mash avocados with lime juice and salt until chunky. Finely dice red onion, tomato, and jalapeño (remove seeds for less heat). Chop coriander. Fold everything into the mashed avocado. Taste and adjust seasoning. Serve immediately with tortilla chips.',
    cookingTime: 10,
    calories: 350,
    servings: 4,
    tags: ['snacks', 'vegan', 'mexican'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '12',
    name: 'Caprese Skewers',
    image: 'https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=600&q=80',
    ingredients: [
      { name: 'Cherry tomatoes', amount: '250', unit: 'g' },
      { name: 'Fresh mozzarella', amount: '200', unit: 'g' },
      { name: 'Fresh basil', amount: '20', unit: 'leaves' },
      { name: 'Balsamic glaze', amount: '2', unit: 'tbsp' },
      { name: 'Olive oil', amount: '1', unit: 'tbsp' },
      { name: 'Salt', amount: '1/4', unit: 'tsp' },
    ],
    instructions: 'Thread a basil leaf, cherry tomato, and small mozzarella ball onto each skewer. Arrange on a serving plate. Drizzle with olive oil and balsamic glaze. Season with salt and black pepper. Serve at room temperature.',
    cookingTime: 10,
    calories: 200,
    servings: 4,
    tags: ['snacks', 'vegetarian', 'italian'],
    createdAt: new Date().toISOString(),
  },
  // --- More breakfast ---
  {
    id: '13',
    name: 'Overnight Oats with Berries',
    image: 'https://images.unsplash.com/photo-1546548970-71785318a17b?w=600&q=80',
    ingredients: [
      { name: 'Rolled oats', amount: '80', unit: 'g' },
      { name: 'Milk', amount: '200', unit: 'ml' },
      { name: 'Greek yogurt', amount: '80', unit: 'g' },
      { name: 'Chia seeds', amount: '1', unit: 'tbsp' },
      { name: 'Honey', amount: '1', unit: 'tbsp' },
      { name: 'Mixed berries', amount: '120', unit: 'g' },
      { name: 'Vanilla extract', amount: '1/2', unit: 'tsp' },
    ],
    instructions: 'Combine oats, milk, yogurt, chia seeds, honey, and vanilla in a jar. Stir well, cover, and refrigerate overnight (at least 6 hours). In the morning, top with fresh mixed berries and an extra drizzle of honey if desired.',
    cookingTime: 5,
    calories: 370,
    servings: 1,
    tags: ['breakfast', 'healthy', 'no-cook'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '14',
    name: 'Scrambled Eggs & Smoked Salmon',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80',
    ingredients: [
      { name: 'Eggs', amount: '3', unit: 'whole' },
      { name: 'Smoked salmon', amount: '80', unit: 'g' },
      { name: 'Cream cheese', amount: '30', unit: 'g' },
      { name: 'Chives', amount: '2', unit: 'tbsp' },
      { name: 'Butter', amount: '1', unit: 'tbsp' },
      { name: 'Sourdough bread', amount: '2', unit: 'slices' },
      { name: 'Black pepper', amount: '1/4', unit: 'tsp' },
    ],
    instructions: 'Whisk eggs with a pinch of salt. Melt butter in a non-stick pan over low heat and add eggs, stirring constantly and gently. Remove from heat while still slightly runny. Toast the sourdough. Spread cream cheese on toast, pile on the soft scrambled eggs, layer over smoked salmon, and finish with chives and black pepper.',
    cookingTime: 12,
    calories: 420,
    servings: 2,
    tags: ['breakfast', 'high-protein', 'quick'],
    createdAt: new Date().toISOString(),
  },
  // --- More lunch ---
  {
    id: '15',
    name: 'Chicken Caesar Wrap',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&q=80',
    ingredients: [
      { name: 'Chicken breast', amount: '250', unit: 'g' },
      { name: 'Large tortilla wraps', amount: '2', unit: 'whole' },
      { name: 'Romaine lettuce', amount: '100', unit: 'g' },
      { name: 'Parmesan', amount: '30', unit: 'g' },
      { name: 'Caesar dressing', amount: '4', unit: 'tbsp' },
      { name: 'Croutons', amount: '30', unit: 'g' },
      { name: 'Lemon juice', amount: '1', unit: 'tbsp' },
    ],
    instructions: 'Season chicken with salt, pepper, and lemon juice. Grill or pan-fry for 6-7 minutes per side. Slice into strips. Warm the tortilla wraps. Toss lettuce with Caesar dressing and croutons. Layer lettuce mixture and chicken strips in the centre of each wrap, top with shaved parmesan, and roll tightly.',
    cookingTime: 20,
    calories: 520,
    servings: 2,
    tags: ['lunch', 'high-protein', 'quick'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '16',
    name: 'Roasted Veggie & Halloumi Salad',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&q=80',
    ingredients: [
      { name: 'Halloumi', amount: '200', unit: 'g' },
      { name: 'Courgette', amount: '1', unit: 'whole' },
      { name: 'Red bell pepper', amount: '1', unit: 'whole' },
      { name: 'Red onion', amount: '1', unit: 'whole' },
      { name: 'Mixed greens', amount: '80', unit: 'g' },
      { name: 'Olive oil', amount: '3', unit: 'tbsp' },
      { name: 'Balsamic vinegar', amount: '2', unit: 'tbsp' },
      { name: 'Honey', amount: '1', unit: 'tsp' },
    ],
    instructions: 'Preheat oven to 200°C. Chop courgette, pepper, and onion into chunks, toss with 2 tbsp olive oil and roast 25 minutes. Slice halloumi and pan-fry until golden on each side. Whisk remaining olive oil, balsamic, and honey for dressing. Arrange greens, roasted veg, and halloumi, then drizzle with dressing.',
    cookingTime: 35,
    calories: 450,
    servings: 2,
    tags: ['lunch', 'vegetarian', 'mediterranean'],
    createdAt: new Date().toISOString(),
  },
  // --- More dinner ---
  {
    id: '17',
    name: 'Beef & Vegetable Stir-Fry',
    image: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&q=80',
    ingredients: [
      { name: 'Beef sirloin', amount: '300', unit: 'g' },
      { name: 'Broccoli', amount: '200', unit: 'g' },
      { name: 'Red bell pepper', amount: '1', unit: 'whole' },
      { name: 'Soy sauce', amount: '3', unit: 'tbsp' },
      { name: 'Sesame oil', amount: '2', unit: 'tsp' },
      { name: 'Garlic', amount: '3', unit: 'cloves' },
      { name: 'Ginger', amount: '1', unit: 'tsp' },
      { name: 'Noodles', amount: '200', unit: 'g' },
    ],
    instructions: 'Slice beef thinly against the grain. Cook noodles according to packet instructions. Heat a wok over high heat. Stir-fry beef for 2 minutes, remove and set aside. Stir-fry broccoli and pepper for 3-4 minutes. Add garlic and ginger, cook 30 seconds. Return beef, add noodles, soy sauce, and sesame oil. Toss everything together and serve.',
    cookingTime: 25,
    calories: 580,
    servings: 2,
    tags: ['dinner', 'high-protein', 'asian'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '18',
    name: 'Baked Lemon Herb Chicken',
    image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=600&q=80',
    ingredients: [
      { name: 'Chicken thighs', amount: '4', unit: 'whole' },
      { name: 'Lemon', amount: '2', unit: 'whole' },
      { name: 'Garlic', amount: '4', unit: 'cloves' },
      { name: 'Rosemary', amount: '2', unit: 'sprigs' },
      { name: 'Thyme', amount: '4', unit: 'sprigs' },
      { name: 'Olive oil', amount: '3', unit: 'tbsp' },
      { name: 'Potatoes', amount: '400', unit: 'g' },
    ],
    instructions: 'Preheat oven to 200°C. Score the chicken thighs and rub with olive oil, lemon zest, crushed garlic, rosemary, and thyme. Halve the potatoes and toss with olive oil and seasoning. Arrange chicken and potatoes in a roasting tin. Pour over the lemon juice. Roast for 40-45 minutes until the chicken skin is golden and the potatoes are tender.',
    cookingTime: 55,
    calories: 610,
    servings: 4,
    tags: ['dinner', 'high-protein', 'comfort'],
    createdAt: new Date().toISOString(),
  },
  // --- 5 more breakfast ---
  {
    id: '19',
    name: 'Açaí Smoothie Bowl',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600&q=80',
    ingredients: [
      { name: 'Frozen açaí puree', amount: '200', unit: 'g' },
      { name: 'Frozen banana', amount: '1', unit: 'whole' },
      { name: 'Almond milk', amount: '100', unit: 'ml' },
      { name: 'Granola', amount: '50', unit: 'g' },
      { name: 'Strawberries', amount: '80', unit: 'g' },
      { name: 'Kiwi', amount: '1', unit: 'whole' },
      { name: 'Honey', amount: '1', unit: 'tbsp' },
      { name: 'Coconut flakes', amount: '2', unit: 'tbsp' },
    ],
    instructions: 'Blend frozen açaí, frozen banana, and almond milk until thick and smooth — it should be thicker than a normal smoothie. Pour into a bowl. Top with granola, sliced strawberries, kiwi, coconut flakes, and a drizzle of honey.',
    cookingTime: 10,
    calories: 390,
    servings: 1,
    tags: ['breakfast', 'vegan', 'healthy'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '20',
    name: 'French Toast with Maple Syrup',
    image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600&q=80',
    ingredients: [
      { name: 'Brioche bread', amount: '4', unit: 'slices' },
      { name: 'Eggs', amount: '3', unit: 'whole' },
      { name: 'Milk', amount: '80', unit: 'ml' },
      { name: 'Vanilla extract', amount: '1', unit: 'tsp' },
      { name: 'Cinnamon', amount: '1/2', unit: 'tsp' },
      { name: 'Butter', amount: '2', unit: 'tbsp' },
      { name: 'Maple syrup', amount: '4', unit: 'tbsp' },
      { name: 'Powdered sugar', amount: '1', unit: 'tbsp' },
    ],
    instructions: 'Whisk eggs, milk, vanilla, and cinnamon in a shallow bowl. Dip each brioche slice and let it soak for 30 seconds per side. Melt butter in a pan over medium heat and cook slices for 2-3 minutes each side until deep golden. Serve dusted with powdered sugar and a generous pour of maple syrup.',
    cookingTime: 15,
    calories: 430,
    servings: 2,
    tags: ['breakfast', 'vegetarian', 'comfort'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '21',
    name: 'Avocado & Feta Toast',
    image: 'https://images.unsplash.com/photo-1603046891744-1f35e64eb271?w=600&q=80',
    ingredients: [
      { name: 'Sourdough bread', amount: '2', unit: 'slices' },
      { name: 'Avocado', amount: '1', unit: 'whole' },
      { name: 'Feta cheese', amount: '50', unit: 'g' },
      { name: 'Cherry tomatoes', amount: '80', unit: 'g' },
      { name: 'Lemon juice', amount: '1', unit: 'tsp' },
      { name: 'Olive oil', amount: '1', unit: 'tbsp' },
      { name: 'Red chilli flakes', amount: '1/4', unit: 'tsp' },
      { name: 'Fresh mint', amount: '5', unit: 'leaves' },
    ],
    instructions: 'Toast the sourdough until golden. Mash avocado with lemon juice and a pinch of salt. Spread thickly on toast. Halve the cherry tomatoes and arrange on top. Crumble over feta, scatter mint leaves, and finish with chilli flakes and a drizzle of olive oil.',
    cookingTime: 10,
    calories: 360,
    servings: 2,
    tags: ['breakfast', 'vegetarian', 'quick'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '22',
    name: 'Breakfast Burrito',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&q=80',
    ingredients: [
      { name: 'Large flour tortillas', amount: '2', unit: 'whole' },
      { name: 'Eggs', amount: '4', unit: 'whole' },
      { name: 'Cheddar cheese', amount: '60', unit: 'g' },
      { name: 'Bacon rashers', amount: '4', unit: 'whole' },
      { name: 'Bell pepper', amount: '1', unit: 'whole' },
      { name: 'Spring onions', amount: '3', unit: 'whole' },
      { name: 'Sour cream', amount: '3', unit: 'tbsp' },
      { name: 'Hot sauce', amount: '1', unit: 'tsp' },
    ],
    instructions: 'Fry bacon until crispy, then set aside. Dice and sauté bell pepper in the bacon fat. Whisk eggs and scramble until just set. Warm the tortillas in a dry pan. Layer scrambled eggs, bacon, sautéed pepper, grated cheese, and spring onions on each tortilla. Add a dollop of sour cream and a dash of hot sauce, then roll tightly.',
    cookingTime: 20,
    calories: 560,
    servings: 2,
    tags: ['breakfast', 'high-protein', 'comfort'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '23',
    name: 'Chia Pudding with Mango',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
    ingredients: [
      { name: 'Chia seeds', amount: '60', unit: 'g' },
      { name: 'Coconut milk', amount: '400', unit: 'ml' },
      { name: 'Honey', amount: '2', unit: 'tbsp' },
      { name: 'Vanilla extract', amount: '1/2', unit: 'tsp' },
      { name: 'Mango', amount: '1', unit: 'whole' },
      { name: 'Lime juice', amount: '1', unit: 'tbsp' },
      { name: 'Toasted coconut', amount: '2', unit: 'tbsp' },
    ],
    instructions: 'Mix chia seeds with coconut milk, honey, and vanilla. Stir well and refrigerate for at least 4 hours (or overnight), stirring once after 30 minutes to prevent clumps. Dice the mango and toss with lime juice. Spoon pudding into glasses and top with mango and toasted coconut.',
    cookingTime: 10,
    calories: 340,
    servings: 2,
    tags: ['breakfast', 'vegan', 'no-cook'],
    createdAt: new Date().toISOString(),
  },
  // --- 5 more lunch ---
  {
    id: '24',
    name: 'Niçoise Salad',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80',
    ingredients: [
      { name: 'Tuna in olive oil', amount: '200', unit: 'g' },
      { name: 'Green beans', amount: '150', unit: 'g' },
      { name: 'Cherry tomatoes', amount: '150', unit: 'g' },
      { name: 'Eggs', amount: '3', unit: 'whole' },
      { name: 'Black olives', amount: '60', unit: 'g' },
      { name: 'New potatoes', amount: '200', unit: 'g' },
      { name: 'Dijon mustard', amount: '1', unit: 'tsp' },
      { name: 'Red wine vinegar', amount: '2', unit: 'tbsp' },
      { name: 'Olive oil', amount: '3', unit: 'tbsp' },
    ],
    instructions: 'Boil potatoes until tender, then cool. Blanch green beans for 3 minutes. Soft-boil eggs for 7 minutes, peel and halve. Whisk mustard, vinegar, and olive oil for dressing. Arrange potatoes, beans, tomatoes, olives, and tuna on a platter. Top with egg halves and drizzle generously with dressing.',
    cookingTime: 30,
    calories: 490,
    servings: 2,
    tags: ['lunch', 'high-protein', 'mediterranean'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '25',
    name: 'Spicy Peanut Noodles',
    image: 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=600&q=80',
    ingredients: [
      { name: 'Rice noodles', amount: '200', unit: 'g' },
      { name: 'Peanut butter', amount: '4', unit: 'tbsp' },
      { name: 'Soy sauce', amount: '3', unit: 'tbsp' },
      { name: 'Sesame oil', amount: '2', unit: 'tsp' },
      { name: 'Sriracha', amount: '2', unit: 'tsp' },
      { name: 'Lime juice', amount: '2', unit: 'tbsp' },
      { name: 'Cucumber', amount: '1', unit: 'whole' },
      { name: 'Spring onions', amount: '3', unit: 'whole' },
      { name: 'Sesame seeds', amount: '1', unit: 'tbsp' },
    ],
    instructions: 'Cook noodles according to packet instructions, then rinse cold. Whisk peanut butter, soy sauce, sesame oil, sriracha, and lime juice with 2 tbsp warm water until smooth. Julienne the cucumber. Toss noodles with sauce and cucumber. Top with sliced spring onions and sesame seeds.',
    cookingTime: 15,
    calories: 480,
    servings: 2,
    tags: ['lunch', 'vegan', 'asian'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '26',
    name: 'Turkey & Avocado Club',
    image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=600&q=80',
    ingredients: [
      { name: 'Sourdough bread', amount: '3', unit: 'slices' },
      { name: 'Turkey breast slices', amount: '120', unit: 'g' },
      { name: 'Avocado', amount: '1', unit: 'whole' },
      { name: 'Bacon rashers', amount: '3', unit: 'whole' },
      { name: 'Lettuce', amount: '2', unit: 'leaves' },
      { name: 'Tomato', amount: '1', unit: 'whole' },
      { name: 'Mayonnaise', amount: '2', unit: 'tbsp' },
      { name: 'Dijon mustard', amount: '1', unit: 'tsp' },
    ],
    instructions: 'Toast all three bread slices. Fry bacon until crispy. Mash avocado with a pinch of salt. Mix mayo and mustard. Spread mayo mix on two slices, avocado on the middle slice. Layer bottom slice with turkey, lettuce, and tomato. Add middle slice avocado-side up. Top with bacon. Add final toast slice and press gently. Slice diagonally.',
    cookingTime: 15,
    calories: 590,
    servings: 1,
    tags: ['lunch', 'high-protein', 'quick'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '27',
    name: 'Minestrone Soup',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80',
    ingredients: [
      { name: 'Cannellini beans', amount: '400', unit: 'g' },
      { name: 'Chopped tomatoes', amount: '400', unit: 'g' },
      { name: 'Vegetable broth', amount: '1', unit: 'L' },
      { name: 'Small pasta', amount: '80', unit: 'g' },
      { name: 'Courgette', amount: '1', unit: 'whole' },
      { name: 'Carrot', amount: '2', unit: 'whole' },
      { name: 'Celery', amount: '2', unit: 'stalks' },
      { name: 'Onion', amount: '1', unit: 'whole' },
      { name: 'Parmesan rind', amount: '1', unit: 'piece' },
      { name: 'Basil', amount: '10', unit: 'leaves' },
    ],
    instructions: 'Sauté diced onion, carrot, and celery in olive oil for 5 minutes. Add courgette and cook 2 minutes. Pour in tomatoes and broth, add parmesan rind and bring to a boil. Add pasta and beans, simmer 10 minutes until pasta is cooked. Remove rind, stir in fresh basil, season well, and serve with a drizzle of olive oil.',
    cookingTime: 35,
    calories: 310,
    servings: 4,
    tags: ['lunch', 'vegan', 'soup'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '28',
    name: 'Falafel Wrap',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&q=80',
    ingredients: [
      { name: 'Falafel balls', amount: '8', unit: 'whole' },
      { name: 'Flatbreads', amount: '2', unit: 'whole' },
      { name: 'Tzatziki', amount: '6', unit: 'tbsp' },
      { name: 'Romaine lettuce', amount: '60', unit: 'g' },
      { name: 'Cherry tomatoes', amount: '100', unit: 'g' },
      { name: 'Red onion', amount: '1/2', unit: 'whole' },
      { name: 'Cucumber', amount: '1/2', unit: 'whole' },
      { name: 'Hot sauce', amount: '1', unit: 'tsp' },
    ],
    instructions: 'Warm falafel in the oven at 180°C for 10 minutes or air-fry until crispy. Warm flatbreads briefly in a dry pan. Spread tzatziki generously on each flatbread. Layer with shredded lettuce, halved tomatoes, thin-sliced red onion, and cucumber. Add four falafel balls per wrap, drizzle with hot sauce, and roll firmly.',
    cookingTime: 15,
    calories: 440,
    servings: 2,
    tags: ['lunch', 'vegetarian', 'mediterranean'],
    createdAt: new Date().toISOString(),
  },
  // --- 5 more dinner ---
  {
    id: '29',
    name: 'Chicken Tikka Masala',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80',
    ingredients: [
      { name: 'Chicken thighs', amount: '600', unit: 'g' },
      { name: 'Tinned tomatoes', amount: '400', unit: 'g' },
      { name: 'Heavy cream', amount: '150', unit: 'ml' },
      { name: 'Onion', amount: '1', unit: 'whole' },
      { name: 'Garlic', amount: '4', unit: 'cloves' },
      { name: 'Ginger', amount: '2', unit: 'tsp' },
      { name: 'Tikka masala paste', amount: '3', unit: 'tbsp' },
      { name: 'Basmati rice', amount: '200', unit: 'g' },
      { name: 'Fresh coriander', amount: '3', unit: 'tbsp' },
    ],
    instructions: 'Marinate chicken in tikka paste and half the ginger for 30 minutes. Grill or char in a hot pan until lightly charred. Sauté onion, garlic, and remaining ginger. Add tikka paste, then tomatoes. Simmer 15 minutes. Stir in cream, add chicken, and cook 10 minutes more. Cook rice separately. Serve garnished with fresh coriander.',
    cookingTime: 50,
    calories: 650,
    servings: 4,
    tags: ['dinner', 'high-protein', 'indian'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '30',
    name: 'Spaghetti Bolognese',
    image: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=600&q=80',
    ingredients: [
      { name: 'Spaghetti', amount: '320', unit: 'g' },
      { name: 'Beef mince', amount: '500', unit: 'g' },
      { name: 'Tinned tomatoes', amount: '400', unit: 'g' },
      { name: 'Tomato paste', amount: '2', unit: 'tbsp' },
      { name: 'Onion', amount: '1', unit: 'whole' },
      { name: 'Garlic', amount: '3', unit: 'cloves' },
      { name: 'Red wine', amount: '100', unit: 'ml' },
      { name: 'Carrot', amount: '1', unit: 'whole' },
      { name: 'Celery', amount: '1', unit: 'stalk' },
      { name: 'Parmesan', amount: '60', unit: 'g' },
    ],
    instructions: 'Finely dice onion, carrot, and celery. Sauté in olive oil until soft, then add minced garlic. Add beef mince and cook until browned. Pour in red wine and let it reduce by half. Stir in tomatoes and paste. Simmer uncovered for 30-40 minutes until rich and thick. Cook spaghetti al dente. Toss pasta with sauce and serve topped with grated parmesan.',
    cookingTime: 60,
    calories: 680,
    servings: 4,
    tags: ['dinner', 'italian', 'comfort'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '31',
    name: 'Garlic Butter Prawn Pasta',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&q=80',
    ingredients: [
      { name: 'King prawns', amount: '300', unit: 'g' },
      { name: 'Linguine', amount: '280', unit: 'g' },
      { name: 'Butter', amount: '3', unit: 'tbsp' },
      { name: 'Garlic', amount: '5', unit: 'cloves' },
      { name: 'White wine', amount: '100', unit: 'ml' },
      { name: 'Cherry tomatoes', amount: '150', unit: 'g' },
      { name: 'Fresh parsley', amount: '3', unit: 'tbsp' },
      { name: 'Lemon', amount: '1', unit: 'whole' },
      { name: 'Chilli flakes', amount: '1/2', unit: 'tsp' },
    ],
    instructions: 'Cook linguine al dente, reserving a cup of pasta water. Melt butter in a wide pan, add sliced garlic and chilli flakes. Cook 1 minute until fragrant. Add prawns and cook 2 minutes per side until pink. Add wine and let it bubble. Add cherry tomatoes and a splash of pasta water. Toss with linguine, parsley, and lemon zest and juice.',
    cookingTime: 25,
    calories: 550,
    servings: 2,
    tags: ['dinner', 'seafood', 'italian'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '32',
    name: 'Mushroom Risotto',
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&q=80',
    ingredients: [
      { name: 'Arborio rice', amount: '320', unit: 'g' },
      { name: 'Mixed mushrooms', amount: '400', unit: 'g' },
      { name: 'Vegetable broth', amount: '1.2', unit: 'L' },
      { name: 'White wine', amount: '150', unit: 'ml' },
      { name: 'Onion', amount: '1', unit: 'whole' },
      { name: 'Garlic', amount: '2', unit: 'cloves' },
      { name: 'Parmesan', amount: '80', unit: 'g' },
      { name: 'Butter', amount: '3', unit: 'tbsp' },
      { name: 'Fresh thyme', amount: '3', unit: 'sprigs' },
    ],
    instructions: 'Keep broth warm in a saucepan. Sauté onion and garlic in butter until soft. Add rice and toast 2 minutes. Pour in wine and stir until absorbed. Add broth one ladle at a time, stirring constantly and waiting for each ladleful to absorb before adding the next, about 18-20 minutes. Meanwhile, sauté mushrooms with thyme. Stir mushrooms and parmesan into the finished risotto. Rest 2 minutes before serving.',
    cookingTime: 40,
    calories: 580,
    servings: 4,
    tags: ['dinner', 'vegetarian', 'italian'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '33',
    name: 'Baked Cod with Mediterranean Veg',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&q=80',
    ingredients: [
      { name: 'Cod fillets', amount: '4', unit: 'whole' },
      { name: 'Cherry tomatoes', amount: '200', unit: 'g' },
      { name: 'Courgette', amount: '1', unit: 'whole' },
      { name: 'Kalamata olives', amount: '60', unit: 'g' },
      { name: 'Capers', amount: '2', unit: 'tbsp' },
      { name: 'Garlic', amount: '3', unit: 'cloves' },
      { name: 'Olive oil', amount: '4', unit: 'tbsp' },
      { name: 'Lemon', amount: '1', unit: 'whole' },
      { name: 'Fresh basil', amount: '10', unit: 'leaves' },
    ],
    instructions: 'Preheat oven to 200°C. Slice courgette and halve tomatoes. Toss veg, olives, capers, and garlic with 3 tbsp olive oil in a large roasting tin. Roast 15 minutes. Push veg to the sides, nestle in cod fillets, drizzle with remaining oil and lemon juice. Season well. Roast another 12-15 minutes until cod is flaking. Scatter basil and serve.',
    cookingTime: 40,
    calories: 380,
    servings: 4,
    tags: ['dinner', 'healthy', 'mediterranean'],
    createdAt: new Date().toISOString(),
  },
  // --- 5 more snacks ---
  {
    id: '34',
    name: 'Edamame with Sea Salt & Chilli',
    image: 'https://images.unsplash.com/photo-1563805642-f32de8ef9f3e?w=600&q=80',
    ingredients: [
      { name: 'Frozen edamame in pods', amount: '400', unit: 'g' },
      { name: 'Sea salt flakes', amount: '1', unit: 'tsp' },
      { name: 'Chilli flakes', amount: '1/4', unit: 'tsp' },
      { name: 'Sesame oil', amount: '1', unit: 'tsp' },
      { name: 'Lime juice', amount: '1', unit: 'tbsp' },
    ],
    instructions: 'Cook edamame in boiling salted water for 4-5 minutes. Drain well and transfer to a bowl. Drizzle with sesame oil and lime juice. Toss to coat. Sprinkle generously with sea salt flakes and chilli flakes. Serve warm or at room temperature — just squeeze the beans out of the pods to eat.',
    cookingTime: 8,
    calories: 150,
    servings: 2,
    tags: ['snacks', 'vegan', 'high-protein'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '35',
    name: 'Rice Cakes with Peanut Butter & Banana',
    image: 'https://images.unsplash.com/photo-1481349518771-20055b2a7b24?w=600&q=80',
    ingredients: [
      { name: 'Rice cakes', amount: '4', unit: 'whole' },
      { name: 'Peanut butter', amount: '4', unit: 'tbsp' },
      { name: 'Banana', amount: '1', unit: 'whole' },
      { name: 'Honey', amount: '1', unit: 'tsp' },
      { name: 'Cinnamon', amount: '1/4', unit: 'tsp' },
      { name: 'Chia seeds', amount: '1', unit: 'tsp' },
    ],
    instructions: 'Spread a tablespoon of peanut butter on each rice cake. Slice the banana into rounds and arrange on top. Drizzle lightly with honey and dust with cinnamon. Sprinkle chia seeds over everything. Serve immediately.',
    cookingTime: 5,
    calories: 210,
    servings: 2,
    tags: ['snacks', 'healthy', 'quick'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '36',
    name: 'Cheese & Charcuterie Board',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&q=80',
    ingredients: [
      { name: 'Brie', amount: '100', unit: 'g' },
      { name: 'Aged cheddar', amount: '80', unit: 'g' },
      { name: 'Prosciutto', amount: '60', unit: 'g' },
      { name: 'Salami', amount: '60', unit: 'g' },
      { name: 'Crackers', amount: '60', unit: 'g' },
      { name: 'Grapes', amount: '100', unit: 'g' },
      { name: 'Walnuts', amount: '30', unit: 'g' },
      { name: 'Honey', amount: '2', unit: 'tbsp' },
    ],
    instructions: 'Allow cheeses to come to room temperature for 30 minutes. Arrange brie and sliced cheddar on a large board. Fold prosciutto into roses and fan out salami slices. Fill gaps with crackers, grapes, and walnuts. Add small pots of honey and any jams or mustards you like. Serve at room temperature for the best flavour.',
    cookingTime: 10,
    calories: 430,
    servings: 3,
    tags: ['snacks', 'vegetarian', 'entertaining'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '37',
    name: 'Crispy Roasted Chickpeas',
    image: 'https://images.unsplash.com/photo-1528748030602-0c027e427e85?w=600&q=80',
    ingredients: [
      { name: 'Chickpeas', amount: '400', unit: 'g' },
      { name: 'Olive oil', amount: '2', unit: 'tbsp' },
      { name: 'Smoked paprika', amount: '1', unit: 'tsp' },
      { name: 'Cumin', amount: '1/2', unit: 'tsp' },
      { name: 'Garlic powder', amount: '1/2', unit: 'tsp' },
      { name: 'Sea salt', amount: '1/2', unit: 'tsp' },
      { name: 'Cayenne pepper', amount: '1/4', unit: 'tsp' },
    ],
    instructions: 'Preheat oven to 220°C. Drain, rinse, and thoroughly pat the chickpeas dry — this is key for crispiness. Toss with olive oil and spread in a single layer on a baking tray. Roast 25-30 minutes, shaking halfway, until golden and crunchy. Remove from oven, toss immediately with all spices and salt. Cool on the tray — they crisp up further as they cool.',
    cookingTime: 35,
    calories: 190,
    servings: 4,
    tags: ['snacks', 'vegan', 'healthy'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '38',
    name: 'Dark Chocolate Almond Bark',
    image: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=600&q=80',
    ingredients: [
      { name: 'Dark chocolate', amount: '200', unit: 'g' },
      { name: 'Roasted almonds', amount: '80', unit: 'g' },
      { name: 'Dried cranberries', amount: '40', unit: 'g' },
      { name: 'Pumpkin seeds', amount: '30', unit: 'g' },
      { name: 'Sea salt flakes', amount: '1/2', unit: 'tsp' },
      { name: 'Orange zest', amount: '1', unit: 'tsp' },
    ],
    instructions: 'Melt chocolate in a heatproof bowl over simmering water, or in the microwave in 30-second bursts. Pour onto a baking tray lined with parchment and spread to about 5mm thick. Quickly scatter almonds, cranberries, pumpkin seeds, orange zest, and sea salt over the surface while the chocolate is still wet. Refrigerate for 1 hour until set. Break into pieces.',
    cookingTime: 15,
    calories: 240,
    servings: 6,
    tags: ['snacks', 'vegetarian', 'no-bake'],
    createdAt: new Date().toISOString(),
  },
];

@Injectable({ providedIn: 'root' })
export class RecipeService {
  private _recipes = signal<Recipe[]>(this.loadFromStorage());

  readonly recipes = this._recipes.asReadonly();

  private loadFromStorage(): Recipe[] {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      let existing: Recipe[] = JSON.parse(stored);
      const sampleMap = new Map(SAMPLE_RECIPES.map(r => [r.id, r]));
      let changed = false;

      const existingIds = new Set(existing.map(r => r.id));
      const newSamples = SAMPLE_RECIPES.filter(r => !existingIds.has(r.id));
      if (newSamples.length > 0) {
        existing = [...existing, ...newSamples];
        changed = true;
      }

      existing = existing.map(r => {
        const sample = sampleMap.get(r.id);
        if (sample && r.image !== sample.image) {
          changed = true;
          return { ...r, image: sample.image };
        }
        return r;
      });

      if (changed) localStorage.setItem(STORAGE_KEY, JSON.stringify(existing));
      return existing;
    }
    localStorage.setItem(STORAGE_KEY, JSON.stringify(SAMPLE_RECIPES));
    return SAMPLE_RECIPES;
  }

  private save() {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(this._recipes()));
  }

  add(recipe: Omit<Recipe, 'id' | 'createdAt'>) {
    const newRecipe: Recipe = {
      ...recipe,
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
    };
    this._recipes.update(r => [...r, newRecipe]);
    this.save();
    return newRecipe;
  }

  update(id: string, data: Omit<Recipe, 'id' | 'createdAt'>) {
    this._recipes.update(r => r.map(rec => rec.id === id ? { ...rec, ...data } : rec));
    this.save();
  }

  delete(id: string) {
    this._recipes.update(r => r.filter(recipe => recipe.id !== id));
    this.save();
  }

  toggleFavourite(id: string) {
    this._recipes.update(r => r.map(rec => rec.id === id ? { ...rec, favourite: !rec.favourite } : rec));
    this.save();
  }

  getById(id: string): Recipe | undefined {
    return this._recipes().find(r => r.id === id);
  }
}
